### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [b-t-k/john-webster_the-duchess-of-malfi#1]
- Looks like this is in British style quotes. Search for `‘` and convert things to American-style. There aren't too many.
- Transcriber is missing `<abbr class="name">` in colophon
- Dedication looks like it's missing header styling. Maybe adding `<header>` and small caps to the first line.
- Note 120: I.e. needs to be capitalized
- There are several incorrect `‘` in the long description

**Comment by acabal** [comment]
In the dedication, the intro is a salutation, not a valediction

**Comment by b-t-k** [comment]
I don't know why I got it into my head that  quotes within dialog should be single but I did... The rest is just a result of me being tired. Sorry about that.
